const json_provincias = [
  { label: 'Albacete', value: 'Albacete' },
  { label: 'Alicante', value: 'Alicante' },
  { label: 'Almería', value: 'Almeria' },
  { label: 'Álava', value: 'Alava' },
  { label: 'Asturias', value: 'Asturias' },
  { label: 'Ávila', value: 'Avila' },
  { label: 'Badajoz', value: 'Badajoz' },
  { label: 'Islas Baleares', value: 'IslasBaleares' },
  { label: 'Barcelona', value: 'Barcelona' },
  { label: 'Burgos', value: 'Burgos' },
  { label: 'Cáceres', value: 'Caceres' },
  { label: 'Cádiz', value: 'Cadiz' },
  { label: 'Cantabria', value: 'Cantabria' },
  { label: 'Castellón', value: 'Castellon' },
  { label: 'Ceuta', value: 'Ceuta' },
  { label: 'Ciudad Real', value: 'CiudadReal' },
  { label: 'Córdoba', value: 'Cordoba' },
  { label: 'A Coruña', value: 'ACorunya' },
  { label: 'Cuenca', value: 'Cuenca' },
  { label: 'Girona', value: 'Girona' },
  { label: 'Granada', value: 'Granada' },
  { label: 'Guadalajara', value: 'Guadalajara' },
  { label: 'Guipúzcoa', value: 'Guipuzcoa' },
  { label: 'Huelva', value: 'Huelva' },
  { label: 'Huesca', value: 'Huesca' },
  { label: 'Jaén', value: 'Jaen' },
  { label: 'León', value: 'Leon' },
  { label: 'Lleida', value: 'Lleida' },
  { label: 'Lugo', value: 'Lugo' },
  { label: 'Madrid', value: 'Madrid' },
  { label: 'Málaga', value: 'Malaga' },
  { label: 'Melilla', value: 'Melilla' },
  { label: 'Murcia', value: 'Murcia' },
  { label: 'Navarra', value: 'Navarra' },
  { label: 'Palencia', value: 'Palencia' },
  { label: 'Las Palmas', value: 'LasPalmas' },
  { label: 'Pontevedra', value: 'Pontevedra' },
  { label: 'La Rioja', value: 'LaRioja' },
  { label: 'Salamanca', value: 'Salamanca' },
  { label: 'Santa Cruz de Tenerife', value: 'SantaCruz' },
  { label: 'Segovia', value: 'Segovia' },
  { label: 'Sevilla', value: 'Sevilla' },
  { label: 'Soria', value: 'Soria' },
  { label: 'Teruel', value: 'Teruel' },
  { label: 'Toledo', value: 'Toledo' },
  { label: 'Valencia', value: 'Valencia' },
  { label: 'Valladolid', value: 'Valladolid' },
  { label: 'Vizcaya', value: 'Vizcaya' },
  { label: 'Zamora', value: 'Zamora' },
  { label: 'Zaragoza', value: 'Zaragoza' }
]

export { json_provincias }
